const enum ErrorStatus {
  NONE = 'NONE',
  SESSION_NOT_EXISTS = 'SESSION_NOT_EXISTS',
  SESSION_FORBIDDEN = 'SESSION_FORBIDDEN',
  MOVE_UNAVAILABLE = 'MOVE_UNAVAILABLE',
  PLAYERS_LIMIT_REACHED = 'PLAYERS_LIMIT_REACHED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  EMPTY_STOCK = 'EMPTY_STOCK',
  SERVER_CLOSED = 'SERVER_CLOSED',
}

export default ErrorStatus;
