export const CURRENT_PLAYER_SET = 'CURRENT_PLAYER_SET';

export const JOINED_PLAYERS_ADD = 'JOINED_PLAYERS_ADD';
export const JOINED_PLAYERS_REMOVE = 'JOINED_PLAYERS_REMOVE';
export const JOINED_PLAYERS_SET = 'JOINED_PLAYERS_SET';

export const LOG_ADD = 'LOG_ADD';

export const PICKED_TILE_SET = 'PICKED_TILE_SET';

export const PLAYER_DECK_SET = 'PLAYER_DECK_SET';

export const COMMON_DECK_SET = 'COMMON_DECK_SET';

export const ROUND_INFO_SET = 'ROUND_INFO_SET';
export const ROUND_INFO_SET_NEXT_MOVE = 'ROUND_INFO_SET_NEXT_MOVE';

export const SESSION_ID_SET = 'SESSION_ID_SET';

export const WAIT_FOR_PLAYERS_SET = 'WAIT_FOR_PLAYERS_SET';

export const SESSION_EMITTER_SET = 'SESSION_EMITTER_SET';

export const FIRST_TILE_SET = 'FIRST_TILE_SET';

export const MOVE_PERMISSION_SET = 'MOVE_PERMISSION_SET';
