name: Domino CI tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          redis-version: '6.x'
      - run: cd server && cp .env.example .env && npm i && npm test
